
POST https://billing-system-0s8q.onrender.com/api/items
Content-Type: application/json

{
  "name": "laptop",
  "description": "laptop is a laptop",
  "image": "https://google.com/image.jpg",
  "price": 898,
  "availableQuantity": 232,
  "allowedMinQuantity": 2,
  "allowedMaxQuantity": 5
}

###

PUT https://billing-system-0s8q.onrender.com/api/items/3
Content-Type: application/json

{
  "name": "laptop",
  "description": "laptop is a good laptop",
  "image": "https://google.com/image.jpg",
  "price": 898,
  "availableQuantity": 232,
  "allowedMinQuantity": 2,
  "allowedMaxQuantity": 5
}


###

GET https://billing-system-0s8q.onrender.com/api/items/3

###

DELETE  https://billing-system-0s8q.onrender.com/api/items/2

###

GET  https://billing-system-0s8q.onrender.com/api/items/paginated?size=5&page=0


