
POST {{baseUrl}}/items
Content-Type: application/json

{
  "name": "laptop",
  "description": "laptop is a laptop",
  "image": "https://google.com/image.jpg",
  "price": 898,
  "availableQuantity": 232,
  "allowedMinQuantity": 2,
  "allowedMaxQuantity": 5
}

###

PUT {{baseUrl}}/items/3
Content-Type: application/json

{
  "name": "laptop",
  "description": "laptop is a good laptop",
  "image": "https://google.com/image.jpg",
  "price": 898,
  "availableQuantity": 232,
  "allowedMinQuantity": 2,
  "allowedMaxQuantity": 5
}


###

GET {{baseUrl}}/items/4
Authorization: Bearer {{token}}

###

DELETE  {{baseUrl}}/items/2

###

GET  {{baseUrl}}/items/paginated?size=30&page=0&sortBy=price&sortDirection=asc&search=soap

###

GET {{baseUrl}}/items/search?query=cheese
Authorization: Bearer {{token}}